name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
        - completed

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull enxxi/v8board-api:latest
    - name: Delete Old docker container
      run: sudo docker rm -f v8board-api-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name v8board-api-container enxxi/v8board-api
